[versions]
infrastructure = "0.19.1"
detekt = "1.23.8"

[libraries]
infrastructure-kotlin = { module = "com.redmadrobot.build:infrastructure-kotlin", version.ref = "infrastructure" }
infrastructure-detekt = { module = "com.redmadrobot.build:infrastructure-detekt", version.ref = "infrastructure" }
infrastructure-publish = { module = "com.redmadrobot.build:infrastructure-publish", version.ref = "infrastructure" }
androidTools-gradle = "com.android.tools.build:gradle:9.0.0"
detektGradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
kotlinGradle = "org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.21"
pluginPublish = "com.gradle.publish:plugin-publish-plugin:2.0.0"
mavenPublishPlugin = "com.vanniktech:gradle-maven-publish-plugin:0.36.0"
gradle-kotlinDsl = "org.gradle.kotlin:gradle-kotlin-dsl-plugins:6.4.2"
jgit = "org.eclipse.jgit:org.eclipse.jgit:7.5.0.202512021534-r"

[plugins]
versions = "com.github.ben-manes.versions:0.53.0"
